---
- hosts: group_ubuntu:group_ubuntu_worker:group_controller_ubuntu

  become: true
  become_method: sudo

  tasks:
    - name: upgrade servers
      apt:
        upgrade: yes
        update_cache: yes
       
