- name: Configure System
  hosts: all
  gather_facts: yes
  become: yes
  # become_method: sudo

  tasks:
    - name: Set DNS
      include_role:
        name: dns
      vars:
        dns_servers:
          - 10.0.50.10
          - 8.8.8.8
        dns_dnssec: true
        dns_domains:
          - nerd.local

    - name: Enable Password Authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication yes'

    - name: Join to AD
      include_role:
        name: thulium_drake.adjoin
      vars:
        adjoin_no_log: "{{ adjoin_no_log }}"
        adjoin_sssd_homedir: "{{ adjoin_sssd_homedir }}"
        adjoin_sssd_default_shell: "{{ adjoin_sssd_default_shell }}"
        adjoin_kerberos_enctypes: "{{ adjoin_kerberos_enctypes }}"
        adjoin_netbios_name: "{{ adjoin_netbios_name }}"
        adjoin_configure_sudo: "{{ adjoin_configure_sudo }}"
        name: "{{ name }}"
        workgroup: "{{ workgroup }}"
        domain_controllers: "{{ domain_controllers }}"
        ldap_base_dn: "{{ ldap_base_dn }}"
        computer_objects_path: "{{ computer_objects_path }}"
        dyndns_update: "{{ dyndns_update }}"
        dyndns_refresh_interval: "{{ dyndns_refresh_interval }}"
        dyndns_ttl: "{{ dyndns_ttl }}"
        dyndns_update_ptr: "{{ dyndns_update_ptr }}"
        linux_admins: "{{ linux_admins }}"
        username: "{{ username }}"
        password: "{{ password }}"

    - name: Disable FQDN in SSSD configuration
      lineinfile:
        path: /etc/sssd/sssd.conf
        regexp: '^use_fully_qualified_names = .*'
        line: 'use_fully_qualified_names = False'

    - name: Reboot the server
      tags: reboot
      become: yes
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the reboot and reconnect
      wait_for:
        port: 22
        host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
        search_regex: OpenSSH
        delay: 30
        timeout: 120
      connection: local

    
