- name: CIS Controls
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
  - name: Harden to CIS Ubuntu 22.04
    include_role:
      name: UBUNTU22-CIS
    vars:
      ubtu22cis_rule_1_1_1_1: true
      ubtu22cis_rule_1_1_1_2: true
      ubtu22cis_rule_1_1_1_3: true
      ubtu22cis_rule_1_1_2_1: true
      ubtu22cis_rule_1_1_2_2: true
      ubtu22cis_rule_1_1_2_3: true
      ubtu22cis_rule_1_1_2_4: true
      ubtu22cis_rule_1_1_3_1: true
      ubtu22cis_rule_1_1_3_2: true
      ubtu22cis_rule_1_1_3_3: true
      ubtu22cis_rule_1_1_4_1: true
      ubtu22cis_rule_1_1_4_2: true
      ubtu22cis_rule_1_1_4_3: true
      ubtu22cis_rule_1_1_4_4: true
      ubtu22cis_rule_1_1_5_1: true
      ubtu22cis_rule_1_1_5_2: true
      ubtu22cis_rule_1_1_5_3: true
      ubtu22cis_rule_1_1_5_4: true
      ubtu22cis_rule_1_1_6_1: true
      ubtu22cis_rule_1_1_6_2: true
      ubtu22cis_rule_1_1_6_3: true
      ubtu22cis_rule_1_1_6_4: true
      ubtu22cis_rule_1_1_7_1: true
      ubtu22cis_rule_1_1_7_2: true
      ubtu22cis_rule_1_1_7_3: true
      ubtu22cis_rule_1_1_8_1: true
      ubtu22cis_rule_1_1_8_2: true
      ubtu22cis_rule_1_1_8_3: true
      ubtu22cis_rule_1_1_9: true
      ubtu22cis_rule_1_1_10: true
      ubtu22cis_rule_1_2_1: true
      ubtu22cis_rule_1_2_2: true
      ubtu22cis_rule_1_3_1: true
      ubtu22cis_rule_1_3_2: true
      ubtu22cis_rule_1_4_1: true
      ubtu22cis_rule_1_4_2: true
      ubtu22cis_rule_1_4_3: true
      ubtu22cis_rule_1_5_1: true
      ubtu22cis_rule_1_5_2: true
      ubtu22cis_rule_1_5_3: true
      ubtu22cis_rule_1_5_4: true
      ubtu22cis_rule_1_6_1_1: true
      ubtu22cis_rule_1_6_1_2: true
      ubtu22cis_rule_1_6_1_3: true
      ubtu22cis_rule_1_6_1_4: true
      ubtu22cis_rule_1_7_1: true
      ubtu22cis_rule_1_7_2: true
      ubtu22cis_rule_1_7_3: true
      ubtu22cis_rule_1_7_4: true
      ubtu22cis_rule_1_7_5: true
      ubtu22cis_rule_1_7_6: true
      ubtu22cis_rule_1_8_1: true
      ubtu22cis_rule_1_8_2: true
      ubtu22cis_rule_1_8_3: true
      ubtu22cis_rule_1_8_4: true
      ubtu22cis_rule_1_8_5: true
      ubtu22cis_rule_1_8_6: true
      ubtu22cis_rule_1_8_7: true
      ubtu22cis_rule_1_8_8: true
      ubtu22cis_rule_1_8_9: true
      ubtu22cis_rule_1_8_10: true
      ubtu22cis_rule_1_9: true
      ubtu22cis_bootloader_password_hash: "grub.pbkdf2.sha512.changethispassword"

