---
- name: CIS Controls
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Harden to CIS Ubuntu 22.04
      include_role:
        name: UBUNTU22-CIS
      vars:
        ubtu22cis_rule_1_1_1_1: true
        ubtu22cis_rule_1_1_1_2: false
        ubtu22cis_rule_1_1_1_3: false
        ubtu22cis_rule_1_1_2_1: false
        ubtu22cis_rule_1_1_2_2: false
        ubtu22cis_rule_1_1_2_3: false
        ubtu22cis_rule_1_1_2_4: false
        ubtu22cis_rule_1_1_3_1: false
        ubtu22cis_rule_1_1_3_2: false
        ubtu22cis_rule_1_1_3_3: false
        ubtu22cis_rule_1_1_4_1: false
        ubtu22cis_rule_1_1_4_2: false
        ubtu22cis_rule_1_1_4_3: false
        ubtu22cis_rule_1_1_4_4: false
        ubtu22cis_rule_1_1_5_1: false
        ubtu22cis_rule_1_1_5_2: false
        ubtu22cis_rule_1_1_5_3: false
        ubtu22cis_rule_1_1_5_4: false
        ubtu22cis_rule_1_1_6_1: false
        ubtu22cis_rule_1_1_6_2: false
        ubtu22cis_rule_1_1_6_3: false
        ubtu22cis_rule_1_1_6_4: false
        ubtu22cis_rule_1_1_7_1: false
        ubtu22cis_rule_1_1_7_2: false
        ubtu22cis_rule_1_1_7_3: false
        ubtu22cis_rule_1_1_8_1: false
        ubtu22cis_rule_1_1_8_2: false
        ubtu22cis_rule_1_1_8_3: false
        ubtu22cis_rule_1_1_9: false
        ubtu22cis_rule_1_1_10: false
        ubtu22cis_rule_1_2_1: false
        ubtu22cis_rule_1_2_2: false
        ubtu22cis_rule_1_3_1: false
        ubtu22cis_rule_1_3_2: false
        ubtu22cis_rule_1_4_1: false
        ubtu22cis_rule_1_4_2: false
        ubtu22cis_rule_1_4_3: false
        ubtu22cis_rule_1_5_1: false
        ubtu22cis_rule_1_5_2: false
        ubtu22cis_rule_1_5_3: false
        ubtu22cis_rule_1_5_4: false
        ubtu22cis_rule_1_6_1_1: false
        ubtu22cis_rule_1_6_1_2: false
        ubtu22cis_rule_1_6_1_3: false
        ubtu22cis_rule_1_6_1_4: false
        ubtu22cis_rule_1_7_1: false
        ubtu22cis_rule_1_7_2: false
        ubtu22cis_rule_1_7_3: false
        ubtu22cis_rule_1_7_4: false
        ubtu22cis_rule_1_7_5: false
        ubtu22cis_rule_1_7_6: false
        ubtu22cis_rule_1_8_1: false
        ubtu22cis_rule_1_8_2: false
        ubtu22cis_rule_1_8_3: false
        ubtu22cis_rule_1_8_4: false
        ubtu22cis_rule_1_8_5: false
        ubtu22cis_rule_1_8_6: false
        ubtu22cis_rule_1_8_7: false
        ubtu22cis_rule_1_8_8: false
        ubtu22cis_rule_1_8_9: false
        ubtu22cis_rule_1_8_10: false
        ubtu22cis_rule_1_9: false
      vars:
        expected_tmp_mnt: fstab
        ubtu22cis_config_aide: false
        ubtu22cis_aide_cron:
          cron_user: root
          cron_file: /etc/cron.d/aide_cron
          aide_job: '/usr/bin/aide --config /etc/aide/aide.conf --check'
          aide_minute: 0
          aide_hour: 5
          aide_day: '*'
          aide_month: '*'
          aide_weekday: '*'
        ubtu22cis_grub_user: root
        ubtu22cis_set_grub_user_pass: false
        ubtu22cis_grub_user_passwd: '$yk0/90QD/Igs'  # Set to changeme
        ubtu22cis_grub_user_file: /etc/grub.d/00_user
        ubtu22cis_set_boot_pass: false
        ubtu22cis_grub_file: /etc/default/grub.cfg
        ubtu22cis_apparmor_disable: false
        ubtu22cis_apparmor_enforce_only: false
        ubtu22cis_disable_dynamic_motd: false
        ubtu22cis_warning_banner: |
          Authorized uses only. All activity may be monitored and reported.
        ubtu22cis_dconf_db_name: local
        ubtu22cis_screensaver_idle_delay: 900  # Set max value for idle-delay in seconds (between 1 and 900)
        ubtu22cis_screensaver_lock_delay: 5    # Set max value for lock-delay in seconds (between 0 and 5)
        ubtu22cis_grub_user_passwd: "grub.pbkdf2.sha512.10000.10086DF439909691B78D8D83E2029169D4D2CCFF3022415DD0B74A319D09139D2AFC776E6C320C75EA393C8A7368BFC4DE27074B981518F0BA1631C196818540.E36C039CA4F7E94D5ECDEA1BBC523D88A247EC0E30F9D02B84AC642F69995269213263FE5C0790CAF155E0D893C86C712514280D5A02FF40A2D54921E52FC1E8"