---
- hosts: group_ubuntu:group_controller_ubuntu:group_ubuntu_worker
  gather_facts: yes
  become: true
  become_user: root


  tasks:
  - name: update apt list
    apt:
      update_cache: yes

  - name: upgrade servers
    apt:
      upgrade: yes
        
       
