---
- hosts: group_ubuntu:group_controller_ubuntu:group_ubuntu_worker
  gather_facts: yes
  become: yes
  become_method: sudo

  tasks:
    - name: upgrade servers
      apt:
        upgrade: yes
        update_cache: yes
       
