---
- hosts: group_ubuntu:group_controller_ubuntu:group_ubuntu_worker
  gather_facts: yes
  become: true
  become_user: root

  tasks:
    - name: upgrade servers
      apt:
        upgrade: yes
        update_cache: yes
       
